# Étudiant : Vincent de Grandpré (DEGV03078209), E26
# Fichier d'intégration continue GitHub pour le projet Labo0
name: LOG430-Lab0_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: Labo0

    steps:
      - name: Checkout dépot  
        uses: actions/checkout@v3

      - name: Créer fichier .env 
        run: |
          echo "CALCULATOR_USERNAME=GithubActions" >> .env

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Éxécuter les tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: | 
          python -m pytest
  
  # Identique à la construction mais sur un noeud auto-hébergé
  deploy:
    runs-on: self-hosted
    # Utilisation d'un conteneur docker pour GitHub Runner
    container:
      image: ubuntu:22.04
    environment: Labo0

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Créer fichier .env 
        run: |
          echo "CALCULATOR_USERNAME=GithubActions" >> .env

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Éxécuter les tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: | 
          python -m pytest
